enum CONST {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',

  SET_IS_SEARCH_OPEN = 'SET_IS_SEARCH_OPEN',
}

export enum FAVOURITE {
  DELETE = 'FAVOURITE_DELETE',
  GET = 'FAVOURITE_GET',
}

export default CONST
